#********** Algorithm Parameters ************

/proc_hydrophone/algorithm/absoluteElevation : false

#********** Filters Parameters ************

/proc_hydrophone/filters/SNR : 0
/proc_hydrophone/filters/maxAngle : 10 #1.57079632679