#********** Algorithm Parameters ************

/proc_hydrophone/algorithm/absoluteElevation : false

#********** Filters Parameters ************

/proc_hydrophone/filters/SNR : 0
/proc_hydrophone/filters/maxDiffAngle : 10
/proc_hydrophone/filters/elevationAngle : 1.57079632679
/proc_hydrophone/filters/flipElevation : true
/proc_hydrophone/filters/removeElevation : true
/proc_hydrophone/filters/minAngle : -2.0944
/proc_hydrophone/filters/maxAngle : 1.0472