#********** Algorithm Parameters ************

/proc_hydrophone/algorithm/absoluteElevation : false

#********** Filters Parameters ************

/proc_hydrophone/filters/SNR : 10
/proc_hydrophone/filters/maxAngle : 1.57079632679